### PR TITLE
Adding recursive xorpad file search and crc32 support

### PR DESCRIPTION
**Pull request by putnam**
Summary:
  Many xorpad repos/distributions now include the CRC32 of the title in the filename. In many cases the xorpad files are also split into multiple subfolders. Currently, 3dsconv will not discover xorpad files in subdirectories or with crc32 info in their filename. In some cases, titles may have multiple revisions. By calculating the crc32 of the input file we can more accurately find its related xorpad.

Changes:
  - The xorpad directory is now searched recursively for xorpad files
  - xorpad files are searched in a case-insensitive fashion
  - Discover and prefer xorpad files with matching crc32 in the filename

Extra info:
  I wrote the CRC32 function included here for minimal memory use and high speed. zlib is about 5x faster than using binascii.crc32.

### CODE REVIEW

**Comment by putnam** [comment]
Need to make a change to this. My break in the file loop is not adequate. Will fix momentarily

**Comment by putnam** [comment]
OK, changes applied and tested.

**Comment by putnam** [comment]
I'm going to collapse these commits together and add another fix, so closing this.

**Comment by ihaveamac** [comment]
"collapse" you mean squash? github already allows doing that at merge-time, so doing it manually is not required anymore.

**Comment by putnam** [comment]
Oh nice, I didn't realize. Was gonna do an --amend on my side. I'll commit one more thing real quick to fix the bug I just came across

**Pull request closed without merging**
